### ISSUE TITLE
Decoupling Checkstatement

### ISSUE THREAD

**Issue by polus-arcticus** [CoopHive/alkahest-mocks#4]
- decoupling checkStatement from the contracts that make attestations (IArbiter from IStatement/IValidator)

https://github.com/CoopHive/tokens-for-docker-alkahest/blob/b7a79093684fe31863228f16306a285bf9db0e25/src/IArbiter.sol#L24

https://github.com/CoopHive/tokens-for-docker-alkahest/blob/b7a79093684fe31863228f16306a285bf9db0e25/src/statements/DockerResultStatement.sol#L45)

https://github.com/CoopHive/tokens-for-docker-alkahest/blob/b7a79093684fe31863228f16306a285bf9db0e25/src/statements/ERC20PaymentStatement.sol#L82

My understanding for this change is that 

https://github.com/CoopHive/tokens-for-docker-alkahest/blob/b7a79093684fe31863228f16306a285bf9db0e25/src/IStatement.sol#L10

is to become something like 

```
abstract contract IStatement is SchemaResolver { ... }
```
and recompile and repass tests

**Comment by mlegls** [comment]
Right. At least ATTESTATION_SCHEMA should be lifted into IStatement, bc IArbiter doesn't need it. Not sure if statements should still be required to have a default checkStatement implementation though. Maybe as a reference to another contract, rather than necessarily its own implementation?
